-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 09:02:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orientacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orientacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orientacion` DEFAULT CHARACTER SET utf8 ;
USE `orientacion` ;

-- -----------------------------------------------------
-- Table `orientacion`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`asesoria` (
  `id_asesoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_as` VARCHAR(100) NULL,
  `dni_as` VARCHAR(25) NULL,
  `titulo_as` VARCHAR(255) NULL,
  `telefono_as` VARCHAR(25) NULL,
  `email_as` VARCHAR(255) NULL,
  `descripcion_as` TEXT NULL,
  `domicilio_as` VARCHAR(255) NULL,
  `fecha_inicio` DATETIME NULL,
  `fecha_fin` DATETIME NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_asesoria`),
  INDEX `fk_asesoria_estados_idx` (`id_estado` ASC),
  CONSTRAINT `fk_asesoria_estados`
    FOREIGN KEY (`id_estado`)
    REFERENCES `orientacion`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`profesores` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `nombre_completo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`reg_acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`reg_acciones` (
  `id_reg_acciones` INT NOT NULL AUTO_INCREMENT,
  `fecha_reg` DATETIME NOT NULL,
  `accion` VARCHAR(255) NOT NULL,
  `automatica` TINYINT NOT NULL DEFAULT 0,
  `id_asesoria` INT NOT NULL,
  `id_profesor` INT NOT NULL,
  PRIMARY KEY (`id_reg_acciones`),
  INDEX `fk_reg_acciones_asesoria1_idx` (`id_asesoria` ASC),
  INDEX `fk_reg_acciones_profesores1_idx` (`id_profesor` ASC),
  CONSTRAINT `fk_reg_acciones_asesoria1`
    FOREIGN KEY (`id_asesoria`)
    REFERENCES `orientacion`.`asesoria` (`id_asesoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_acciones_profesores1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `orientacion`.`profesores` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  `departamento_corto` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orientacion`.`profesores_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orientacion`.`profesores_departamento` (
  `id_profesores_departamento` INT NOT NULL AUTO_INCREMENT,
  `id_profesor` INT NOT NULL,
  `rol_id_rol` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_profesores_departamento`),
  INDEX `fk_profesores_departamento_profesores1_idx` (`id_profesor` ASC),
  INDEX `fk_profesores_departamento_rol1_idx` (`rol_id_rol` ASC),
  INDEX `fk_profesores_departamento_departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_profesores_departamento_profesores1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `orientacion`.`profesores` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_departamento_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `orientacion`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_departamento_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `orientacion`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
